{
 "title": "实例监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_pod_labels, label_instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "HDFS总容量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(name_node_capacity_total * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})/2"
    }
   ]
  },
  {
   "title": "InceptorSqlFailedTasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inceptor_server_sql_failed_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "HDFS使用总量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(name_node_capacity_used  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})/2"
    }
   ]
  },
  {
   "title": "InceptorSqlCompletedTasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inceptor_server_sql_completed_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "HDFS剩余容量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(name_node_capacity_remaining  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})/2"
    }
   ]
  },
  {
   "title": "InceptorSqlActiveTasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inceptor_server_sql_active_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "InceptorSqlFailedTaskPercent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(inceptor_server_sql_failed_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})/(sum(inceptor_server_sql_failed_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})+sum(inceptor_server_sql_completed_tasks  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"}))"
    }
   ]
  }
 ]
}