{
 "title": "实例监控—kafka、mysql",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_pod_labels, label_instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "AllTopicsMessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_topics_messages_in_per_sec * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mysql_global_status_sort_scan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_sort_scan   * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "AllTopicsBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_topics_bytes_out_per_sec * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mysql_global_status_uptime ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_uptime  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "AllTopicsBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_topics_bytes_in_per_sec * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mysql_global_status_slow_queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_slow_queries* on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "kafka_live_brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_live_brokers * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mysql_global_status_connections ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_connections * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "kafka_dead_brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_dead_brokers * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mysql_global_status_queries ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_queries * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  }
 ]
}