{
 "title": "监控实例-----cpu、mem",
 "description": "监控集群租户实例的cpu、内存、存储情况",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_pod_labels, label_instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(kubelet:pod:cpu:used, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(kubelet:pod:mem:used, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})/1024/1024/1024"
    }
   ]
  },
  {
   "title": "存储",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "instance",
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(warpdrive_volume_used_space_bytes  * on (pod) group_left(label_instance_id) kube_pod_labels{label_instance_id=\"$instance\"})"
    }
   ]
  }
 ]
}