{
 "title": "租户使用率",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet:namespace:cpu:usage{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet:namespace:mem:usage{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "存储使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(warpdrive_volume_used_space_bytes{exported_namespace=\"$namespace\"})/sum(warpdrive_volume_total_space_bytes{exported_namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}