{
 "title": "集群租户总览",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem",
 "tags": [ "namespace" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet:namespace:cpu:used{namespace=~\"^$Namespace$\"})"
    }
   ]
  },
  {
   "title": "Request CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"})"
    }
   ]
  },
  {
   "title": "Namespace CPU Used [core]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)(rate(container_cpu_usage_seconds_total{namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Request [cores]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Exceed[percentage]",
   "type": "graph",
   "description": "cpu used/cpu request",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (namespace:node:pod:cpu:used:requests{namespace=~\"$Namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Memory",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kubelet:namespace:mem:used{namespace=~\"^$Namespace$\"})"
      }
     ]
    },
    {
     "title": "Request Memory",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"}) "
      }
     ]
    },
    {
     "title": "Namespace Memory Used [bytes]",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"^$Namespace$\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace Memory Request [bytes]",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace Memory Exceed[percentage]",
     "type": "graph",
     "description": "Memory Used/Requests",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (namespace:node:pod:mem:used:requests{namespace=~\"$Namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Volume Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (warpdrive_volume_used_space_ratio{namespace=~\"$Namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace Volume Used & Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum by  (namespace) (warpdrive_volume_used_space_bytes{namespace=~\"$Namespace\"} / 1024 /1024)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum by (namespace) (warpdrive_volume_used_space_bytes{namespace=~\"$Namespace\"} / 1024 /1024 / warpdrive_volume_used_space_ratio)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Networks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Network Usage [percent]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kubelet:namespace:network_received:used{namespace=~\"^$Namespace$\"}",
       "legendFormat": "{{namespace}}|Received"
      },
      {
       "expr": "kubelet:namespace:network_sent:used{namespace=~\"^$Namespace$\"}",
       "legendFormat": "{{namespace}}|Sent"
      }
     ]
    }
   ]
  }
 ]
}