{
 "title": "Search on Shiva",
 "description": "DIsplay New search key metrics from Prometheus",
 "tags": [ "prometheus newSearch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "thread_pool",
    "label": "thread Pool",
    "query": "label_values(sh_server_threadpool_threads_number, name)"
   },
   { "name": "interval", "label": "interval", "query": "30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "tabletServer",
    "label": "TabletServer",
    "query": "label_values(sh_server_jvm_uptime_millis,server)"
   },
   { "name": "job", "label": "job", "query": "label_values(ALERTS, job)" },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "alertstate", "label": "alertstate", "query": "firing, pending" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Alerts",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"critical\"} > 0) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Warnings Alerts",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} > 0) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Max  Load Average 1m",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "max (node_load1)" }
     ]
    },
    {
     "title": "Min Memory Available",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(node_memory_MemAvailable_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Tcp Established",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(node_netstat_Tcp_CurrEstab)"
      }
     ]
    },
    {
     "title": "Prometheus Targets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "count(up)" }
     ]
    }
   ]
  },
  {
   "title": "Alerts detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current critical alerts table",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"critical\"} == 1) by (alertname,job,server,severity,description,summary,value)",
       "legendFormat": "instance: {{instance}}  alertname: {{alertname}}"
      },
      {}
     ]
    },
    {
     "title": "Critical Alert Graph: instance alertname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Alert number" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"critical\"} == 1)  by (alertname,server)",
       "legendFormat": "{{server}}  {{alertname}}"
      }
     ]
    },
    {
     "title": "Current warnings alert table",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} == 1) by (alertname,job,server,severity,description,summary,value)",
       "legendFormat": "instance: {{instance}}  alertname: {{alertname}}"
      }
     ]
    },
    {
     "title": "Warnings Alert Graph: instance alertname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Alert number" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "count(ALERTS{job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} == 1)  by (alertname,server)",
       "legendFormat": "{{server}} {{alertname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table number not in trash",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sh_cluster_table_not_in_trash_number",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Table number in trash",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sh_cluster_table_in_trash_number",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster data size",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sh_server_tables_store_size_bytes)"
      }
     ]
    },
    {
     "title": "Documents count (with replicas)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sh_server_tables_docs_number)"
      }
     ]
    },
    {
     "title": "TabletServer number",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sh_cluster_server_number", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Active server number",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sh_cluster_avtive_server_number"
      }
     ]
    },
    {
     "title": "Jeopardy server number",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sh_cluster_jeopardy_server_number",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Inavtive server number",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sh_cluster_inavtive_server_number",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tablet number",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sh_cluster_tablet_number" }
     ]
    }
   ]
  },
  {
   "title": "OS Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "Percentage (%)" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "percentunit", "label": "Percentage (%)" }
     ],
     "targets": [
      {
       "expr": "1 - ((avg_over_time(node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s])) / avg_over_time(node_memory_MemTotal_bytes[30s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "Percentage (%)" }
     ],
     "targets": [
      {
       "expr": "100*(1-(sum by (instance) (node_filesystem_avail_bytes))/(sum by (instance) (node_filesystem_size_bytes)))"
      }
     ]
    },
    {
     "title": "Disk Read & Write Latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "Percentage (%)" }
     ],
     "targets": [
      {
       "expr": "100*(sum by (instance) (irate(node_disk_read_time_seconds_total[1m])))/(sum by (instance) (irate(node_disk_reads_completed_total[1m])))",
       "legendFormat": "{{instance}}-read"
      },
      {
       "expr": "100*(sum by (instance) (irate(node_disk_write_time_seconds_total[1m])))/(sum by (instance) (irate(node_disk_writes_completed_total[1m])))",
       "legendFormat": "{{instance}}-write"
      }
     ]
    },
    {
     "title": "Disk I/O Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      { "expr": "irate(node_disk_io_now[1d])" }
     ]
    },
    {
     "title": "Disk I/O Utility",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "percentunit", "label": "Utility" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total[1d])"
      }
     ]
    },
    {
     "title": "Network Sent Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total[1d])"
      }
     ]
    },
    {
     "title": "Available inodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "percent", "label": "Percentage (%)" }
     ],
     "targets": [
      {
       "expr": "100*(sum by (instance) (node_filesystem_files_free))/(sum by (instance) (node_filesystem_files))"
      }
     ]
    }
   ]
  },
  { "title": "Process Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap used bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes", "label": "Heap used bytes" }
     ],
     "targets": [
      {
       "expr": "sh_server_jvm_mem_heap_used_bytes",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Heap used percent",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "percent", "label": "Heap used percent" }
     ],
     "targets": [
      {
       "expr": "sh_server_jvm_mem_heap_used_percent",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Nonheap used bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "decbytes", "label": "Nonheap used bytes" }
     ],
     "targets": [
      {
       "expr": "sh_server_jvm_mem_nonheap_used_bytes",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "GC collection time seconds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s", "label": "GC collection time seconds" }
     ],
     "targets": [
      {
       "expr": "sh_server_jvm_gc_collection_time_seconds"
      }
     ]
    },
    {
     "title": "GC time percentage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "percentunit", "label": "GC time percentage" }
     ],
     "targets": [
      {
       "expr": "irate(sh_server_jvm_gc_collection_time_seconds[1d])",
       "legendFormat": "{{server}} - {{gc}}"
      }
     ]
    },
    {
     "title": "GC collection count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "GC collection count" }
     ],
     "targets": [
      {
       "expr": "irate(sh_server_jvm_gc_collection_count[1d])"
      }
     ]
    },
    {
     "title": "JVM threads number",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "Threads number" }
     ],
     "targets": [
      { "expr": "sh_server_jvm_threads_number", "legendFormat": "{{server}}" }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Search query rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Queries/s" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_search_query_count[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Documents indexing latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "((rate(sh_server_tables_indexing_index_time_millis[$interval])) / 1000) / rate(sh_server_tables_indexing_index_count[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Documents indexing count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Time per second" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_indexing_index_count[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Documents deleting rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_doc_deleted_number[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Search contexts number",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Contexts number" }
   ],
   "targets": [
    {
     "expr": "sh_server_tables_search_context_count"
    }
   ]
  },
  {
   "title": "Search query latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Query latency" }
   ],
   "targets": [
    {
     "expr": "((rate(sh_server_tables_search_query_time_millis[$interval]))/1000) / rate(sh_server_tables_search_query_count[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Search fetch rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Fetches/s" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_search_fetch_count[$interval])"
    }
   ]
  },
  {
   "title": "Search fetch latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Fetch latency" }
   ],
   "targets": [
    {
     "expr": "((rate(sh_server_tables_search_fetch_time_millis[$interval])/1000) / rate(sh_server_tables_search_fetch_count[$interval])) / 1000",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Indices refresh rate in bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "Refresh size in bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_refresh_total_size_in_bytes[$interval])"
    }
   ]
  },
  {
   "title": "Indices refresh latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "Refresh latency" }
   ],
   "targets": [
    {
     "expr": "((rate(sh_server_tables_refresh_total_time_millis[$interval]))/1000) / rate(sh_server_tables_refresh_total_count[$interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Indices refresh rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Refresh count/s" }
   ],
   "targets": [
    {
     "expr": "rate(sh_server_tables_refresh_total_count[$interval])"
    }
   ]
  },
  {
   "title": "Documents indexing avg time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "(rate(sh_server_tables_indexing_index_time_millis[$interval]) * 1000) / (rate(sh_server_tables_indexing_index_count[$interval]))"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments number",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Segments number" }
     ],
     "targets": [
      {
       "expr": "sh_server_tables_segments_count"
      }
     ]
    },
    {
     "title": "Segments memory size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes", "label": "Segments memory size" }
     ],
     "targets": [
      {
       "expr": "sh_server_tables_segments_memory_in_bytes",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices merging rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Merges/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_merge_total_number[$interval])"
      }
     ]
    },
    {
     "title": "Indices merging rate in documents",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_merge_total_docs_count[$interval])"
      }
     ]
    },
    {
     "title": "Indices merging rate in bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Merge size in bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_merge_total_size_bytes[$interval])"
      }
     ]
    },
    {
     "title": "Indices merge latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "((rate(sh_server_tables_merge_total_time_millis[$interval]))/1000) / rate(sh_server_tables_merge_total_number[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Average merge throttling time per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s", "label": "Time per second" }
     ],
     "targets": [
      {
       "expr": "(rate(sh_server_tables_merge_total_throttled_time_millis[$interval])) / 1000",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices commit rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Commit/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_commit_total_number[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Indices commit latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "((rate(sh_server_tables_commit_total_time_millis[$interval]))/1000) / rate(sh_server_tables_commit_total_number[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average IO throttling time per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time per second" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_store_throttle_time_in_nanos[$interval]) / 1000000000",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Store data size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes", "label": "Data size" }
     ],
     "targets": [
      {
       "expr": "sh_server_tables_store_size_bytes",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "sh_server_tables_querycache_cache_size"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_querycache_evictions_count[$interval])"
      }
     ]
    },
    {
     "title": "Query cache hits",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Hits/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_querycache_hit_count[$interval])"
      }
     ]
    },
    {
     "title": "Query cache misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Misses/s" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_tables_querycache_miss_number[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - Threads Pool Utility",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "thread_pool",
   "collapsed": true,
   "panels": [
    {
     "title": "$thread_pool pool utility",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "repeat": "thread_pool",
     "yaxes": [
      { "format": "percentunit", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "(sh_server_threadpool_threads_number{server=~\"$tabletServer\",name=\"$thread_pool\",type=\"active\"} / on(server) sh_server_threadpool_threads_number{server=~\"$tabletServer\",name=\"$thread_pool\",type=\"threads\"})",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - Queued Tasks Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "$thread_pool queued tasked",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "repeat": "thread_pool",
     "yaxes": [
      { "format": "short", "label": "Task number" }
     ],
     "targets": [
      {
       "expr": "sh_server_threadpool_tasks_number{server=~\"$tabletServer\",name=\"$thread_pool\"}",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool - Rejected Threads Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "$thread_pool queued tasked",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "repeat": "thread_pool",
     "yaxes": [
      { "format": "short", "label": "Task number" }
     ],
     "targets": [
      {
       "expr": "rate(sh_server_threadpool_threads_count{server=~\"$tabletServer\",name=\"$thread_pool\",type=\"rejected\"}[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics collection count in $interval",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Metrics count" }
     ],
     "targets": [
      {
       "expr": "delta(sh_metrics_generate_time_seconds_count[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Metrics collection latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "delta(sh_metrics_generate_time_seconds_sum[$interval]) / delta(sh_metrics_generate_time_seconds_count[$interval])",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  }
 ]
}