{
 "title": "SQL-HBASE随申码集群监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hbase Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hbase_requests{namespace=\"a21jqv3\",pod=\"hbmaster-a21jqv3-metrics-54c855fcbb-8nhs6\"}"
    }
   ]
  },
  {
   "title": "Node_IPVS_Outgoing_pps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "每1小时的访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"a21jqv3\",pod=\"hbmaster-a21jqv3-metrics-54c855fcbb-s4rrm\"}[1h])"
    }
   ]
  },
  {
   "title": "每5分钟的访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"a21jqv3\",pod=\"hbmaster-a21jqv3-metrics-54c855fcbb-s4rrm\"}[5m])"
    }
   ]
  },
  {
   "title": "Hbase Cluster Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbregionserver-qkhzx.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "HBase Cluster Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_cpu_usage:sum{pod_name=~\".*hbregionserver-qkhzx.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}