{
 "title": "随申码埋点数据集群监控",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "独立用户数",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rest_uv_count{namespace=\"32m8iru\",rest_uv_count=\"rest_uv_count\",service=\"hbmaster-32m8iru-metrics-hl\"})"
    }
   ]
  },
  {
   "title": "累计访问量",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rest_pv_count{namespace=\"32m8iru\",rest_pv_count=\"rest_pv_count\",service=\"hbmaster-32m8iru-metrics-hl\"})"
    }
   ]
  },
  {
   "title": "Node_IPVS_Outgoing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_bytes_total{node_name=\"datanode067\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_bytes_total{node_name=\"datanode067\"}[5m])\n",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "Node Network Package",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{node_name=\"datanode067\",device=~\"bond.*\"}[1m])",
     "legendFormat": "{{node_name}}-receive_drop_total"
    },
    {
     "expr": "-irate(node_network_receive_drop_total{node_name=\"datanode067\",device=~\"bond.*\"}[1m])",
     "legendFormat": "{{node_name}}-transmit_drop"
    }
   ]
  },
  {
   "title": "Node_IPVS_Outgoing_pps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_packets_total{node_name=\"datanode067\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_packets_total{node_name=\"datanode067\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "IPVS Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_exporter:node_cpu_use:percent{instance=\"172.27.148.230:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hbase Cluster Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbregionserver-5hp4w.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Hbase Cluster Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbregionserver-5hp4w.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "IPVS Node Memory  Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{node_name=\"datanode067\"}",
     "legendFormat": "{{node_name}}-avaliable"
    },
    {
     "expr": "node_memory_Cached_bytes{node_name=\"datanode067\"}",
     "legendFormat": "{{node_name}}-cache"
    }
   ]
  },
  {
   "title": "每五分钟日志写入次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{namespace=\"32m8iru\",handler=\"AccessLogController.addLog\"}[5m]))"
    }
   ]
  },
  {
   "title": "当前日志批量写入延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(enterprise_log_batch_insert_latency_sum{namespace=\"32m8iru\"}) /sum(enterprise_log_batch_insert_latency_count{namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "当前接收日志总数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(total_enterprise_log_count{namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "Rest Server Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbasehealth-65df656d94-.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "http总请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{handler=\"AccessLogController.addLog\",namespace=\"32m8iru\"}[5m]))"
    }
   ]
  },
  {
   "title": "日志批量写入延迟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(access_log_batch_insert_latency_sum{namespace=\"32m8iru\"}) / sum(access_log_batch_insert_latency_count{namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "日志写入总延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(access_log_batch_insert_latency_sum{namespace=\"32m8iru\"}[5m])"
    }
   ]
  },
  {
   "title": "调用时间分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(http_response_time_millis_histogram_sum{namespace=\"32m8iru\",handler=\"AccessLogController.addLog\"} )"
    }
   ]
  },
  {
   "title": "http进行中的请求数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(http_requests_inflight{namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "日志队列长度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "access_log_queue_size{namespace=\"32m8iru\"}"
    }
   ]
  },
  {
   "title": "调用时间分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_response_time_millis_histogram_sum{namespace=\"32m8iru\",handler=\"AccessLogController.addLog\"}[5m]) )"
    }
   ]
  },
  {
   "title": "调用时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_response_time_millis{namespace=\"32m8iru\",handler='AccessLogController.addLog'}"
    }
   ]
  },
  {
   "title": "接收日志总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(total_access_log_count{namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "http request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"HealthController.getHealth\",namespace=\"32m8iru\"})"
    }
   ]
  },
  {
   "title": "延迟大于1s的请求数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_time_millis_histogram_count{handler=\"HealthCheckController.healthCheck\",status=\"200\",service=\"hbasehealth-server-svc\",namespace=\"32m8iru\"} ) - sum(http_response_time_millis_histogram_bucket{handler=\"HealthCheckController.healthCheck\",status=\"200\",le=\"1000.0\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"})",
     "legendFormat": "数量"
    }
   ]
  },
  {
   "title": "当前日志队列长度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "enterprise_log_queue_size{namespace=\"32m8iru\"}"
    }
   ]
  },
  {
   "title": "Rest Server Http Requests",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 69 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"HealthController.getHealth\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"})"
    }
   ]
  },
  {
   "title": "每个Server平均访问时间",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_millis_sum{handler=\"HealthController.getHealth\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"}) by (pod) / avg(http_response_time_millis_count{handler=\"HealthController.getHealth\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"}) by (pod)"
    }
   ]
  },
  {
   "title": "RestServer 每5分钟的http请求",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"32m8iru\",service=\"hbasehealth-server-svc\",handler=\"HealthController.getHealth\"}[5m]))"
    }
   ]
  },
  {
   "title": "Rest Server Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 79 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_cpu_usage:sum{pod_name=~\"hbasehealth-684dc47d5-.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "RestServer 每5分钟的http GET请求",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"32m8iru\",service=\"hbasehealth-server-svc\",handler=\"HealthController.getHealth\", method=\"GET\"}[5m]))"
    }
   ]
  },
  {
   "title": "RestServer 每5分钟的http POST请求",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"32m8iru\",service=\"hbasehealth-server-svc\",handler=\"HealthController.getHealth\", method=\"POST\"}[5m]))"
    }
   ]
  },
  {
   "title": "Hyperbase Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 89 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(hbase_requests{namespace=\"32m8iru\",service=\"hbmaster-32m8iru-metrics-hl\"})"
    }
   ]
  },
  {
   "title": "平均访问时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_millis_sum{handler=\"HealthController.getHealth\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"}) / avg(http_response_time_millis_count{handler=\"HealthController.getHealth\",namespace=\"32m8iru\",service=\"hbasehealth-server-svc\"})",
     "legendFormat": "request_avg_latancy"
    }
   ]
  }
 ]
}