{
 "title": "随申码集群网络状况",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Hbase Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(hbase_requests{namespace=\"2ca6w9n\"})"
    }
   ]
  },
  {
   "title": "Node_IPVS_Outgoing_pps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "每小时的访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"2ca6w9n\",service=\"hbmaster-2ca6w9n-metrics-hl\"}[1h])"
    }
   ]
  },
  {
   "title": "每5分钟的访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"2ca6w9n\",service=\"hbmaster-2ca6w9n-metrics-hl\"}[5m])"
    }
   ]
  },
  {
   "title": "IPVS Node Memory  Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{node_name=\"datanode037\"}",
     "legendFormat": "{{node_name}}-avaliable"
    },
    {
     "expr": "node_memory_Cached_bytes{node_name=\"datanode037\"}",
     "legendFormat": "{{node_name}}-cache"
    }
   ]
  },
  {
   "title": "IPVS Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_exporter:node_cpu_use:percent{instance=\"172.27.148.200:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node_IPVS_Outgoing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_bytes_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_bytes_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "Node Network Package",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{node_name=\"datanode037\",device=~\"bond.*\"}[1m])",
     "legendFormat": "{{node_name}}-receive_drop_total"
    },
    {
     "expr": "-irate(node_network_receive_drop_total{node_name=\"datanode037\",device=~\"bond.*\"}[1m])",
     "legendFormat": "{{node_name}}-transmit_drop"
    }
   ]
  },
  {
   "title": "Hbase Cluster Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbregionserver-v4g88.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "HBase Cluster Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_cpu_usage:sum{pod_name=~\".*hbregionserver-v4g88.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"2ca6w9n\"}",
     "legendFormat": "{{deployment}}-Expect"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"2ca6w9n\"}",
     "legendFormat": "{{deployment}}-Status"
    }
   ]
  },
  {
   "title": "每5分钟的访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"a21jqv3\"}[5m])"
    }
   ]
  }
 ]
}