{
 "title": "随申码生产集群监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "累计独立用户数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rest_uv_count{namespace=\"2ca6w9n\",rest_uv_count=\"rest_uv_count\"}"
    }
   ]
  },
  {
   "title": "累计访问量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"2ca6w9n\",handler=\"HealthController.getHealth\"}[10h]))"
    }
   ]
  },
  {
   "title": "随申码 每5分钟的http请求",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"2ca6w9n\",handler=\"HealthController.getHealth\"}[5m]))"
    }
   ]
  },
  {
   "title": "随申码平均响应时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_millis_sum{handler=\"HealthController.getHealth\",namespace=\"2ca6w9n\"}) / avg(http_response_time_millis_count{handler=\"HealthController.getHealth\",namespace=\"2ca6w9n\"})",
     "legendFormat": "request_avg_latancy"
    }
   ]
  },
  {
   "title": "随申码每5分钟的访问量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"2ca6w9n\"}[5m])"
    }
   ]
  },
  {
   "title": "随申码每小时的访问量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(hbase_requests{namespace=\"2ca6w9n\"}[1h])"
    }
   ]
  },
  {
   "title": "随申码每秒查询次数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_packets_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "随申码查询带宽流量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_ipvs_outgoing_bytes_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-outgoing"
    },
    {
     "expr": "-irate(node_ipvs_incoming_bytes_total{node_name=\"datanode037\"}[5m])",
     "legendFormat": "{{node_name}}-incoming"
    }
   ]
  },
  {
   "title": "随申码 每5分钟的http请求POST(支付宝)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"2ca6w9n\",handler=\"HealthController.getHealth\",method=\"POST\"}[5m]))"
    }
   ]
  },
  {
   "title": "每个Server平均访问时间",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_millis_sum{handler=\"HealthController.getHealth\",namespace=\"2ca6w9n\"}) by (pod) / avg(http_response_time_millis_count{handler=\"HealthController.getHealth\",namespace=\"2ca6w9n\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Hyperbase 集群内存使用",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_memory_usage_bytes:sum{pod_name=~\".*hbregionserver-v4g88.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "随申码 每5分钟的http请求GET(其他)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_requests_total{namespace=\"2ca6w9n\",handler=\"HealthController.getHealth\",method=\"GET\"}[5m]))"
    }
   ]
  },
  {
   "title": "随申码 Http Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"HealthController.getHealth\",namespace=\"2ca6w9n\"})"
    }
   ]
  },
  {
   "title": "延迟大于1s的请求数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_time_millis_histogram_count{handler=\"HealthController.getHealth\",status=\"200\",namespace=\"2ca6w9n\"}) - sum(http_response_time_millis_histogram_bucket{handler=\"HealthController.getHealth\",status=\"200\",le=\"1000.0\",namespace=\"2ca6w9n\"})",
     "legendFormat": "数量"
    }
   ]
  },
  {
   "title": "HBase 集群CPU使用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kubelet:pod:cpu:used{namespace=~\"2ca6w9n\",pod_name=~\".*hbregionserver-v4g88.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Hyperbase集群累计访问量",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(hbase_requests{namespace=\"2ca6w9n\"})"
    }
   ]
  }
 ]
}